---
title: "Schedule"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

\

Course material will be uploaded here throughout the week.

# Day 1

```{r, echo = FALSE}
library(kableExtra)
urls <- c("slides/day-01.html",NA,NA,"slides/day-01.html#26",NA,NA,"slides/revisiting-statistics.pdf")
dt <- data.frame(schedule = c("Course introduction",
                              "Group exercise: mini reading group", #30-45 mins
                              "Break (15 mins)", #15 mins 11:00
                              "Introduction to hypothesis testing", #45 min lecture 12:00
                              "Lunch (45 mins)", # 45 mins  13:00
                              "Group exercise: defining hypothesis", #30 minutes
                              "(Re)Introducting some statistics")) #45 minutes
dt$schedule[1] <- paste0("[", dt$schedule[1], "](", urls[1], ")")
dt$schedule[4] <- paste0("[", dt$schedule[4], "](", urls[4], ")")
dt$schedule[7] <- paste0("[", dt$schedule[7], "](", urls[7], ")")
kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

# Slides
```

Further reading:

* [Learning statistics with R: Chapter 1 and Chapter 11](https://learningstatisticswithr.com/book/why-do-we-learn-statistics.html)
* [tinystats.github.io/teacups-giraffes-and-statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/)



# Day 2

```{r, echo = FALSE}
library(kableExtra)
urls <- c("slides/reproducibility.pdf","slides/test-statistics.pdf",NA,NA,NA,NA,NA)
dt <- data.frame(schedule = c("Intro to reproducibility and data accessibility",
                              "Group exercise: tracking down data",
                              "Group exercise: reproducibility workflows",
                              "Lunch break (45 mins)",
                              "Statistical tests"))
                 
dt$schedule[1] <- paste0("[", dt$schedule[1], "](",
                         urls[1], ")")
dt$schedule[5] <- paste0("[", dt$schedule[5], "](", urls[2], ")")

kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

# Slides
```

* [Learning statistics with R: Chapter 1 and Chapter 11](https://learningstatisticswithr.com/book/why-do-we-learn-statistics.html)

# Day 3

```{r, echo = FALSE}
library(kableExtra)
urls <- c("slides/test-statistics2.pdf",NA,NA,NA,NA,NA,NA)
dt <- data.frame(schedule = c("Statistical test II",
                              "Group exercise: identifying tests",
                              "Lunch break (60 mins)",
                              "Work on presentation"))
                 
dt$schedule[1] <- paste0("[", dt$schedule[1], "](", urls[1], ")")
kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

# Slides
```


* [How to perform tukey HSD test in R](https://www.r-bloggers.com/2021/08/how-to-perform-tukey-hsd-test-in-r/)
* [Learning statistics with R: Chapter 13 and Chapter 14](https://learningstatisticswithr.com/book/why-do-we-learn-statistics.html)

# Day 4

```{r, echo = FALSE}
library(kableExtra)
urls <- c("slides/test-statistics2.pdf","https://www.dominos.de/speisekarte",NA,NA,NA,NA,NA)
dt <- data.frame(schedule = c("Work on presentations",
                              "Lunch break (45 mins)",
                              "Presentation 1 (13:30)",
                              "Presentation 2 (14:00)",
                              "Presentation 3 (14:30)",
                              "Pizza!"))
                 
dt$schedule[1] <- paste0("[", dt$schedule[1], "](", urls[1], ")")
dt$schedule[6] <- paste0("[", dt$schedule[6], "](", urls[2], ")")
kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

# Slides
```


